### ISSUE TITLE
[BUG] - New source tab opens on every single step for the same file if you launch the debuggee with no tabs opened

### ISSUE THREAD

**Issue by DeliciousLines** [EpicGamesExt/raddebugger#260] opened 2024-06-08 08:55 UTC
Version: v0.9.10 alpha (Jun 8 2024)

Steps to reproduce:
- Make sure there are no tabs.
- Launch the debuggee and break at the entry point.
- Step several times, this should open a new source tab for the same file every single time.

Expected behaviour:
- Only open a source tab once for the same file.

**Comment by ryanfleury** [comment] 2024-06-08 15:07
This seems like a duplicate of #86, and so it is likely being caused by the "File Path Map". Can you open that UI and show me what is in it, and send me your `raddbg_user` and `raddbg_project` files?

**Comment by DeliciousLines** [comment] 2024-06-09 09:02
Sure! Here is a screenshot of the file path map:

<img width="643" alt="filepath_map - The RAD Debugger (0 9 10 ALPHA) - Jun  8 2024  821b600   Debug" src="https://github.com/EpicGamesExt/raddebugger/assets/116554116/c72cb220-40f2-41d2-b378-ed8b98f31ff5">

And here are the files:
[bug_report_user_and_project.zip](https://github.com/user-attachments/files/15751232/bug_report_user_and_project.zip)

**Comment by ryanfleury** [comment] 2024-06-13 22:35
Thanks for sending this over, and sorry for the late response, I've been deep in another rabbit hole. This is likely being caused by that entry in the "File Path Map". It isn't doing anything (since there is no destination path), so if you delete it, do you still notice the issue?

**Comment by DeliciousLines** [comment] 2024-06-14 08:08
No problem. Deleting the entry solves the issue, the client only opens one tab as expected.

**Comment by ryanfleury** [comment] 2024-06-17 20:02
This behavior should be resolved, but let me know if you run into it again, or if you notice any more behavior which incorrectly led to that "blank path map" situation.

**Closed by ryanfleury** 2024-06-17 20:02 UTC
Labels: Bug, Duplicate
