### ISSUE TITLE
Holds on to EXE even after terminating debugging process, breaking recompiles

### ISSUE THREAD

**Issue by GoldenbergDaniel** [EpicGamesExt/raddebugger#179] opened 2024-03-27 17:32 UTC
When debugging an executable compiled with Odin, the debugger seems to hold on to the executable even after the debugging process is killed, resulting in a failed recompilation of the project. I have to recompile twice after debugging.

The build command I used is `odin build src -out=debug\Game.exe -debug`.

I also tried the flag `-lld` instead of `-debug`, and this time I get a file called "Game.exe.tmp0" after recompiling. This file persists until I exit the debugger application, after which it gets deleted (along with later iterations such as tmp1).

**Comment by GoldenbergDaniel** [comment] 2024-03-27 17:35
I tested this with my C project, and I get the same issue. I have to delete the executable to properly recompile it.

**Comment by ryanfleury** [comment] 2024-03-27 17:44
Hmm, it looks like this may have been introduced after some newer changes I made to the demon/ctrl layers, if you're using the top of `master`. I've reproduced it on my end using that version. Does the same issue persist if you use the prebuilt 0.9.8 version?

**Comment by GoldenbergDaniel** [comment] 2024-03-27 17:56
I just tested 0.9.8 with both C and Odin, both without issue. However, something else I noticed in both the latest build and 0.9.8 is that I can't kill the process by hitting the stop button when debugging my Odin project. I'm not sure if this has to do with it being compiled in Odin, or the fact that it's a terminal application. I do not have this issue with my C window application.

**Comment by ryanfleury** [comment] 2024-03-27 17:58
Great. Looks like raddbg is keeping a handle open to the EXE, currently unclear how that regression was introduced but looking into it now.

As for the process-killing issue, can you send me a small Odin executable which reproduces that issue?

**Comment by GoldenbergDaniel** [comment] 2024-03-27 18:07
This is just a basic terminal application that waits for command input in an infinite loop.
[TestExe.zip](https://github.com/EpicGamesExt/raddebugger/files/14779400/TestExe.zip)

**Comment by ryanfleury** [comment] 2024-03-27 18:22
The EXE handle not being correctly closed has been fixed in 4899f1871b1c2203b64251c85db626998b662db0. This isn't on the `master` branch yet but will be probably by later today. You can build from `dev` and have the issue resolved (although keep in mind that there are a few other things I'm working on there in the meantime).

Looking into the terminal application killing issue now.

**Comment by ryanfleury** [comment] 2024-03-28 15:44
Halting and killing should now always work as of 291bf3875d8bfb688d360dc2d099417c0a1b2625.

**Closed by ryanfleury** 2024-03-28 15:44 UTC
