### ISSUE TITLE
Incorrect stepping behaviour when stepping over int3 in disassembly view

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#223] opened 2024-05-24 04:36 UTC
After hitting the int3 instruction if you try and step one instruction in the disassembly view it will erroneously skip the next instruction.
For example, if you try stepping one instruction after the int3 here it will step to the second nop, skipping the first nop instruction.
![image](https://github.com/EpicGamesExt/raddebugger/assets/105329747/6af9ec86-e9b0-4c42-b028-51f3fb5da18f)

```
#include <stdio.h>
#include <stdint.h>
#include <windows.h>
int main(void) {
    printf("1\n");
    
    VOID *code = VirtualAlloc(0, 0x1000, MEM_COMMIT|MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    *((uint32_t*)code) = 0xC39090CC;

    ((void (__fastcall *)()) code)();

    printf("2\n");
    return 0;
}
```

**Comment by ryanfleury** [comment] 2024-05-24 15:22
Fixed in 9349ac9e7225b8c81ff7d543467540e4b92b1512.

This was caused by a poorly-thought-through hack of mine to avoid this slightly confusing situation:
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/9bbd6f0d-4196-41aa-82b5-185c853363f2)

It was more intuitive to me that the thread show at the trap address, not the post-trap address. But this is clearly more of a visualization issue, not a functionality issue, so I've removed that hack, and have put on my to-do list to address this visualization issue at the frontend layer only.

**Closed by ryanfleury** 2024-05-24 15:22 UTC
