### ISSUE TITLE
String comparison for conditional breakpoint

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#213] opened 2024-05-16 10:38 UTC
String comparison doesn't work in conditional breakpoints.
The way it works in visual studio is by doing strcmp() in the condition field but I think we can do better :)

**Comment by ryanfleury** [comment] 2024-09-28 00:08
This is now in `dev` and will be in 0.9.12 (though as I have said elsewhere, I don't recommend using `dev` just yet, since a few regressions are still being fixed).

The way this will work is you can use pointer comparison with a string literal in the evaluation system. In other words, this can now be evaluated:

`some_ptr_in_program == "Hello, World!"`

And it can be used in conditional breakpoints as well.

**Closed by ryanfleury** 2024-09-28 00:08 UTC
Labels: Feature Request
