### ISSUE TITLE
Freeze then trying edit expression.

### ISSUE THREAD

**Issue by Wc4ever** [EpicGamesExt/raddebugger#362] opened 2024-11-12 21:44 UTC
Raddebugger freeze then I trying to edit expression while inspecting it as an array. In my particular case I'm trying to watch std::vector (MSVC) of structs.

Here is video:

https://github.com/user-attachments/assets/6e738c32-bda6-493e-8dc9-353c46fa3eab

**Comment by ryanfleury** [comment] 2024-11-12 21:45
Which version are you running?

**Comment by ryanfleury** [comment] 2024-11-12 21:52
Does this issue still happen if you pull from `dev` and build the debugger locally? I can't seem to reproduce it at the moment on the top of `dev`. If the issue still happens for you then the issue may be caused by your local configuration, and so if that's the case then I'll ask for the files in `%appdata%/raddbg`.

**Comment by Wc4ever** [comment] 2024-11-13 11:54
Can't reproduce it on `dev` branch also. Seems I need to switch to dev build since it more stable.

**Comment by ryanfleury** [comment] 2024-11-14 21:09
It is variable, we try to keep `master` more stable, but `dev` is where we actively work, so it is more volatile (we fix things there first, and we also break things there first). In any case, this will be in the next release. Please let me know if it happens again. Thanks!

**Closed by ryanfleury** 2024-11-14 21:09 UTC
