### ISSUE TITLE
Menus don't prevent hovering on underlying items

### ISSUE THREAD

**Issue by cmuratori** [EpicGamesExt/raddebugger#239] opened 2024-05-29 02:12 UTC
Currently, if the user moves over a pull-down menu and then moves the mouse around the menu area, hover-tips will still display for elements _underneath_ the menu that should not be reachable. The UI system may need to have a "catch-all" that blocks mouse interaction from propagating below open menu boxes.

\- Casey

**Comment by ryanfleury** [comment] 2024-05-29 04:53
Did you notice this specifically the hover tooltips that show the full contents of truncated text, e.g. hovering `foo...` showing `foobar` as a tooltip? I've reproduced that, if so. That goes through a different path (since it is kind of a "meta" path, that does catch-all interaction across the entire UI tree, rather than being a sort of "standard" interaction), and so this *shouldn't* be happening for anything else, but let me know if that is false.

**Comment by ryanfleury** [comment] 2024-05-29 17:57
The bug I mentioned is fixed as of 0e179f3844f62a74a2baf702e1434d31d32276a7, but let me know if this was a different issue and I can re-open this and investigate.

**Closed by ryanfleury** 2024-05-29 17:57 UTC
Labels: Bug

**Comment by cmuratori** [comment] 2024-05-29 18:00
I believe the bug was as you described it (only truncated things). I can't be sure, but I'll re-open if I see it resurface after this fix.

Thanks,
\- Casey
