### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kshanik** [EpicGamesExt/raddebugger#176] opened 2024-03-21 04:26 UTC
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
1. [0x7ff698d0e667] df_eval_watch_view_build +22663, df_views.c line 1669
2. [0x7ff698c8940a] df_view_ui_Watch +154, df_views.c line 6721
3. [0x7ff698d4d82d] df_window_update_and_render +150925, df_gfx.c line 5708
4. [0x7ff698dab3b4] update_and_render +5300, raddbg.c line 285
5. [0x7ff698d58e94] entry_point +5844, raddbg.c line 577
6. [0x7ff698dad863] WinMain +771, raddbg_main.cpp line 348
7. [0x7ff698db54e2] __scrt_common_main_seh +262, exe_common.inl line 288
8. [0x7ffbc19e7344] KERNEL32
9. [0x7ffbc34e26b1] ntdll

Version: 0.9.8 [c757388]

[Close]

**Comment by ryanfleury** [comment] 2024-03-21 23:17
Duplicate of #133, fixed in e637f7237c338ead02026e15754f44b2cf15429e, which isn't on `master` just yet. But you can get this fix via `dev`.

**Closed by ryanfleury** 2024-03-21 23:17 UTC
