### ISSUE TITLE
AVX-512 instructions are not recognized in Disassembly window

### ISSUE THREAD

**Issue by michal-z** [EpicGamesExt/raddebugger#259] opened 2024-06-06 13:00 UTC
Tested with 0.9.10 ALPHA.

**Comment by ratchetfreak** [comment] 2024-06-12 10:54
duplicate of #169 

the disassembly library currently used doesn't support the newfangled x86 extensions.

**Comment by michal-z** [comment] 2024-06-12 20:38
This issue is specifically about AVX-512. #169 is about AVX/AVX2.

**Comment by ratchetfreak** [comment] 2024-06-13 08:32
same issue though, the OP in the issue literally says

> Quickly looking at the library, seems like there is no AVX-512 support either.

**Comment by ryanfleury** [comment] 2024-07-23 23:30
Fixed as of ccf8504dd1209503905dfb97a0210f2a20e2acaa.

**Closed by ryanfleury** 2024-07-23 23:30 UTC
Labels: Bug, Duplicate, Visualization, Missing Support
