### ISSUE TITLE
Regression - no debug info for hot-loaded DLL

### ISSUE THREAD

**Issue by ofrank123** [EpicGamesExt/raddebugger#228] opened 2024-05-24 23:49 UTC
I have a hot reloading setup, where I copy a DLL (so that it is not locked) to a new file and then load that copied dll, like so:
`my_lib.dll` -> `my_lib_TMP.dll`
In raddbg 0.9.9, the debugger has no problem finding the debug info, however in raddbg 0.9.10, there seems to be no debug information available for the dll (stepping into the dll from the main exe does not work, nor does setting breakpoints in the dll code.  In addition, I noticed that no `.rdi` file was generated for the DLL, despite the presence of a PDB.)  I noticed in the patch notes that some behavior around hot reloading has been changed, maybe I am missing some new step?

**Comment by ryanfleury** [comment] 2024-05-25 00:00
Hm - there is a test that does exactly this, and it is working on my end, so there must be some detail that explains the difference. Is it possible for you to send me the DLL/PDB, or a minimally reproducing version?

Also, can you double check the timestamps on the EXE, DLL, PDB files? I suspect it may have something to do with some changes I made to some internal caching layers.

**Comment by ofrank123** [comment] 2024-05-25 10:43
Yeah, I'll try to get to get a small repro setup.  It doesn't feel like it'd make a difference, but I'm using Zig, so it may be doing something when generating the `pdb` that you don't test?  Here's a picture of the timestamps, as you can see they are the same, except for the copied DLL:
![raddbg_hot-reload-bug](https://github.com/EpicGamesExt/raddebugger/assets/15386897/c8e2ad08-9364-4427-b49c-949211883578)

**Comment by ofrank123** [comment] 2024-05-25 13:30
Here's a minimal repro of the issue: [REPO](https://github.com/ofrank123/raddbg-hot-reload-issue)

**Comment by ryanfleury** [comment] 2024-05-26 05:55
What version are you using? I am getting the following error when building:
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/d6ceef06-a865-4a4f-b32c-8fb166c06066)

**Comment by ofrank123** [comment] 2024-05-26 19:22
My `zig version` reads `0.12.0` I haven't tested it on any other versions (as I don't know if you're on an older or newer version) but I just changed the build script to not use the `LazyPath` directly, as that approach is deprecated anyways on 0.12.0 (although through an obscure comment...), and now seems to be removed on master (so I'm assuming you're using a more recent version than me).  Let me know if the fix I pushed works for you!

**Comment by ryanfleury** [comment] 2024-05-26 20:16
That works, thanks!

I've diagnosed the bug. One of the core changes to allow for a different form of hot-reloading (EXE hot-reloading, via trampling over the PEB table) required the debug info cache layer to be a bit more restrictive about its keys, and basically in this situation the debug info caching layer incorrectly rejects the PDB, because it is older than the copied DLL.

I'll fix this and report back.

**Comment by ryanfleury** [comment] 2024-05-26 20:25
Fixed in 15f5894c608ef44f87b2e229a3d4942531726944.

**Closed by ryanfleury** 2024-05-26 20:25 UTC

**Comment by ofrank123** [comment] 2024-05-27 13:16
Thanks Ryan!
