### ISSUE TITLE
Crash while launching and closing target multiple times 

### ISSUE THREAD

**Issue by TheSandvichMaker** [EpicGamesExt/raddebugger#246] opened 2024-05-30 00:00 UTC
There might not be a causal link, but I triggered the crash while switching between my debug and release target and launching and closing them repeatedly just to compare their startup times. This crash happened right after I hit shift+f5 to shut down the target.

[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGames/raddebugger/issues

Call stack:
1. [0x7ff634277858] df_core_end_frame +1208, df_core.c line 8865
2. [0x7ff63435d73d] update_and_render +5229, raddbg.c line 360
3. [0x7ff6342f16a3] entry_point +6323, raddbg_main.cpp line 395
4. [0x7ff634305dce] main_thread_base_entry_point +1390, base_entry_point.c line 84
5. [0x7ff6343697cb] wWinMain +363, os_core_win32.c line 1814
6. [0x7ff63436a05e] __scrt_common_main_seh +262, exe_common.inl line 288
7. [0x7ff802c0257d] KERNEL32
8. [0x7ff8049caa48] ntdll

Version: 0.9.10 [325474f]

[Close]

**Comment by mistymntncop** [comment] 2024-05-30 00:16
looks like a duplicate of (https://github.com/EpicGamesExt/raddebugger/issues/243)
try updating.

**Comment by ryanfleury** [comment] 2024-05-30 15:12
Yeah I think this has been fixed, just pull + build, and let me know if you catch it happening again.

**Closed by ryanfleury** 2024-05-30 15:12 UTC
