### ISSUE TITLE
Fatal Exception when clicking around in the watch window

### ISSUE THREAD

**Issue by tmpvar** [EpicGamesExt/raddebugger#174] opened 2024-03-17 20:21 UTC
```
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
1. [0x7ff70ca5fe46] df_eval_watch_view_build +33078, df_views.c line 1652
2. [0x7ff70c9de5d8] df_view_ui_Watch +168, df_views.c line 6721
3. [0x7ff70ca23069] df_window_update_and_render +151209, df_gfx.c line 5707
4. [0x7ff70ca637b1] update_and_render +4369, raddbg.c line 286
5. [0x7ff70ca7ad47] entry_point +5671, raddbg.c line 577
6. [0x7ff70c8a245d] WinMain +877, raddbg_main.cpp line 348
7. [0x7ff70ca7c98e] __scrt_common_main_seh +262, exe_common.inl line 288
8. [0x7ffc53617344] KERNEL32
9. [0x7ffc545626b1] ntdll

Version: 0.9.8 [c757388]

[Close]
```

I'm not exactly sure what was clicked when this happened, but here's a screenshot 

![image](https://github.com/EpicGamesExt/raddebugger/assets/46673/721efa62-a626-4fb1-ad0a-2f2b269e4adf)

**Comment by ryanfleury** [comment] 2024-03-21 23:18
This looks like a duplicate of #133, which was fixed in e637f7237c338ead02026e15754f44b2cf15429e. This change is not yet on `master`, but you can get it if you `git checkout dev` and build on that branch.

**Closed by ryanfleury** 2024-03-21 23:18 UTC
